import type { MealAttributes, MealIngredient, MealStep } from '../meals.model.js';

/**
 * The seeded recipe base.
 *
 * This is the product's moat. A generic recipe API can return "jollof rice";
 * it cannot tell you to fry the base until the oil floats, or that the rice
 * should sit level with the water and no higher. These are written the way a
 * Nigerian home cook would explain them to someone in their kitchen.
 *
 * Every ingredient carries a `catalogueId`, which is what the matcher runs on —
 * matching on names alone would break the moment a cook typed "atarodo".
 *
 * `optional: true` means the meal is still itself without it. Optional
 * ingredients never count as missing, so a cook is not told they cannot make
 * jollof because they are out of bay leaves.
 */

type SeedIngredient = [catalogueId: string, name: string, qty: number | null, unit: string | null, optional?: boolean];

interface SeedMeal {
  slug: string;
  name: string;
  cuisines: string[];
  difficulty: 'easy' | 'medium' | 'involved';
  cookTimeMinutes: number;
  serves: number;
  heroIcon: string;
  description: string;
  whatMakesItGood: string;
  ingredients: SeedIngredient[];
  steps: [heading: string, description: string, minutes: number][];
}

const SEEDS: SeedMeal[] = [
  {
    slug: 'jollof-rice',
    name: 'Jollof Rice',
    cuisines: ['Nigerian', 'West African'],
    difficulty: 'medium',
    cookTimeMinutes: 70,
    serves: 6,
    heroIcon: 'plateJollofRice',
    description:
      'The party staple. Rice cooked in a fried pepper-and-tomato base until every grain takes the colour, finished low and slow so the bottom catches just enough.',
    whatMakesItGood:
      'The smoky bottom. Jollof lives or dies on how long you fry the base before the rice goes in — rush it and you get red rice, take your time and you get jollof.',
    ingredients: [
      ['rice_long_grain', 'Long-grain rice', 4, 'cup'],
      ['tomato', 'Tomatoes', 6, 'piece'],
      ['tatashe', 'Tatashe', 2, 'piece'],
      ['scotch_bonnet', 'Scotch bonnet', 2, 'piece'],
      ['onion_red', 'Red onions', 2, 'piece'],
      ['tomato_paste', 'Tomato paste', 1, 'tin'],
      ['groundnut_oil', 'Groundnut oil', 150, 'ml'],
      ['stock_cube', 'Stock cubes', 3, 'piece'],
      ['thyme_dry', 'Dried thyme', 1, 'tsp'],
      ['curry_powder', 'Curry powder', 1, 'tsp'],
      ['bay_dry', 'Bay leaves', 2, 'piece', true],
      ['salt', 'Salt', null, null],
    ],
    steps: [
      ['Blend the base', 'Blend the tomatoes, tatashe, scotch bonnet and one onion until smooth. Do not add water — the tomatoes carry enough of their own.', 8],
      ['Reduce the blend', 'Pour the blend into a dry pot and boil it down until the water is gone and it thickens. Skipping this is why jollof turns out watery.', 15],
      ['Fry the base', 'Heat the oil, slice in the second onion and fry until translucent. Add the tomato paste and fry two minutes, then the reduced blend. Fry until the oil separates and floats to the top and the raw smell is gone. This is the step that makes it jollof.', 18],
      ['Season', 'Stir in the stock cubes, thyme, curry and bay leaves. Taste it now — this is the last easy moment to fix the salt.', 3],
      ['Add the rice', 'Wash the rice until the water runs clear, then stir it into the base. Add water until it sits level with the rice, not above it.', 5],
      ['Steam it down', 'Cover tightly, lowest heat. Do not stir and do not lift the lid for twenty minutes. Foil under the lid helps if yours does not seal.', 20],
      ['Finish', 'Check a grain. If it needs more, sprinkle a little hot water at the edges and cover again. Take it off, leave it five minutes, then stir from the bottom up.', 5],
    ],
  },
  {
    slug: 'egusi-soup',
    name: 'Egusi Soup',
    cuisines: ['Nigerian', 'West African'],
    difficulty: 'medium',
    cookTimeMinutes: 60,
    serves: 6,
    heroIcon: 'potStew',
    description: 'Ground melon seed cooked in palm oil until it lumps and thickens, with leafy greens and whatever meat is in the house.',
    whatMakesItGood: 'The lumps. Egusi fried properly holds together in soft clumps rather than dissolving into a paste — that texture is the whole point, and it comes from frying it in the oil before any water goes near it.',
    ingredients: [
      ['egusi_ground', 'Ground egusi', 300, 'g'],
      ['palm_oil', 'Palm oil', 200, 'ml'],
      ['ugu', 'Ugu leaves', 1, 'bunch'],
      ['beef', 'Beef', 500, 'g'],
      ['ponmo', 'Ponmo', 200, 'g', true],
      ['dried_fish', 'Dried fish', 100, 'g'],
      ['crayfish', 'Crayfish', 3, 'tbsp'],
      ['onion_red', 'Red onions', 1, 'piece'],
      ['scotch_bonnet', 'Scotch bonnet', 3, 'piece'],
      ['stock_cube', 'Stock cubes', 2, 'piece'],
      ['iru', 'Iru', 1, 'tbsp', true],
      ['salt', 'Salt', null, null],
    ],
    steps: [
      ['Cook the meat', 'Season the beef and ponmo with onion, one stock cube and salt. Cook covered in its own liquid until tender, adding water only if it threatens to burn. Keep the stock.', 25],
      ['Fry the egusi', 'Heat the palm oil until it thins but does not smoke. Stir the ground egusi into a thick paste with a little stock, drop it in spoonfuls, and let it fry without stirring until the lumps set.', 10],
      ['Build the soup', 'Pour in the reserved stock a little at a time so the lumps stay whole. Add the blended pepper, crayfish, iru and the dried fish.', 8],
      ['Simmer', 'Cover and let it cook until the oil rises to the top. Taste for salt.', 12],
      ['Add the greens', 'Stir in the ugu and take it off the heat almost immediately — the residual heat is enough, and a boiled leaf loses its bite.', 3],
    ],
  },
  {
    slug: 'efo-riro',
    name: 'Efo Riro',
    cuisines: ['Nigerian', 'West African'],
    difficulty: 'medium',
    cookTimeMinutes: 45,
    serves: 5,
    heroIcon: 'potStew',
    description: 'A Yoruba vegetable stew where the greens are the point, not a garnish — cooked in a fried pepper base with iru and assorted meat.',
    whatMakesItGood: 'The pepper base is fried down hard before the greens go in, so the vegetables stay bright and firm rather than stewing into mush.',
    ingredients: [
      ['spinach', 'Spinach', 2, 'bunch'],
      ['tatashe', 'Tatashe', 3, 'piece'],
      ['scotch_bonnet', 'Scotch bonnet', 3, 'piece'],
      ['onion_red', 'Red onions', 1, 'piece'],
      ['palm_oil', 'Palm oil', 150, 'ml'],
      ['iru', 'Iru', 1, 'tbsp'],
      ['crayfish', 'Crayfish', 2, 'tbsp'],
      ['dried_fish', 'Dried fish', 100, 'g'],
      ['beef', 'Beef', 400, 'g', true],
      ['ponmo', 'Ponmo', 150, 'g', true],
      ['stock_cube', 'Stock cubes', 2, 'piece'],
      ['salt', 'Salt', null, null],
    ],
    steps: [
      ['Prepare the greens', 'Wash the spinach well, slice it, and squeeze out as much water as you can. Wet greens water down the whole pot.', 8],
      ['Blend the pepper', 'Roughly blend the tatashe, scotch bonnet and half the onion. Leave it coarse — efo riro wants texture, not a smooth sauce.', 5],
      ['Fry the base', 'Heat the palm oil, fry the remaining sliced onion, then add the pepper blend. Fry until it darkens and the oil separates.', 12],
      ['Add the flavour', 'Stir in iru, crayfish, stock cubes and the dried fish, plus the meat and its stock if you are using it. Simmer.', 10],
      ['Fold in the greens', 'Add the squeezed spinach and fold rather than stir. Two minutes on the heat, no more, then off.', 3],
    ],
  },
  {
    slug: 'ofada-rice-ayamase',
    name: 'Ofada Rice and Ayamase',
    cuisines: ['Nigerian'],
    difficulty: 'involved',
    cookTimeMinutes: 90,
    serves: 6,
    heroIcon: 'basketRice',
    description: 'Local unpolished rice with the green pepper sauce known as designer stew — bleached palm oil, green peppers, and assorted meat.',
    whatMakesItGood: 'The bleached palm oil. Heating the oil until it turns clear is what gives ayamase its particular smoky depth, and nothing else substitutes for it.',
    ingredients: [
      ['rice_ofada', 'Ofada rice', 3, 'cup'],
      ['green_pepper', 'Green chilli', 400, 'g'],
      ['green_bell', 'Green bell pepper', 4, 'piece'],
      ['palm_oil', 'Palm oil', 300, 'ml'],
      ['onion_red', 'Red onions', 2, 'piece'],
      ['iru', 'Iru', 2, 'tbsp'],
      ['beef', 'Beef', 400, 'g'],
      ['shaki', 'Shaki', 200, 'g', true],
      ['ponmo', 'Ponmo', 200, 'g', true],
      ['egg_chicken', 'Eggs', 4, 'piece', true],
      ['crayfish', 'Crayfish', 2, 'tbsp'],
      ['stock_cube', 'Stock cubes', 3, 'piece'],
      ['moin_moin_leaf', 'Moin moin leaves', 6, 'piece', true],
    ],
    steps: [
      ['Cook the meats', 'Season and boil the beef, shaki and ponmo separately until each is tender — they take very different times. Keep every drop of the stock.', 35],
      ['Blend the peppers', 'Blend the green chillies, bell peppers and one onion coarsely, then boil the blend down until almost dry.', 15],
      ['Bleach the oil', 'Heat the palm oil on medium until it stops smoking heavily and turns clear. Open a window. This is what makes it ayamase and there is no shortcut.', 10],
      ['Fry the sauce', 'Fry the second onion in the bleached oil, add iru, then the reduced pepper. Fry until the oil floats clear on top.', 15],
      ['Finish the sauce', 'Add the meats, crayfish, stock cubes and enough stock to loosen it. Simmer, then fold in halved boiled eggs.', 12],
      ['Cook the rice', 'Parboil the ofada rice, rinse it well to take the local edge off, then steam until tender. Serve in the leaves if you have them.', 30],
    ],
  },
  {
    slug: 'beans-and-plantain',
    name: 'Beans and Fried Plantain',
    cuisines: ['Nigerian', 'West African'],
    difficulty: 'easy',
    cookTimeMinutes: 65,
    serves: 4,
    heroIcon: 'bagBeans',
    description: 'Soft brown beans cooked down with palm oil and pepper, served with sweet fried plantain.',
    whatMakesItGood: 'The contrast. Savoury, slightly smoky beans against plantain fried until the sugars catch — it is the cheapest complete meal in the country and one of the best.',
    ingredients: [
      ['beans_brown', 'Brown beans', 2, 'cup'],
      ['plantain_ripe', 'Ripe plantain', 3, 'piece'],
      ['palm_oil', 'Palm oil', 100, 'ml'],
      ['onion_red', 'Red onions', 1, 'piece'],
      ['scotch_bonnet', 'Scotch bonnet', 2, 'piece'],
      ['groundnut_oil', 'Groundnut oil', 200, 'ml'],
      ['stock_cube', 'Stock cubes', 2, 'piece'],
      ['crayfish', 'Crayfish', 1, 'tbsp', true],
      ['salt', 'Salt', null, null],
    ],
    steps: [
      ['Boil the beans', 'Pick over the beans, rinse, and boil in plenty of water. Do not salt yet — salt early keeps beans hard.', 40],
      ['Check for softness', 'A bean should crush easily between two fingers. If the water runs low top it up with hot, never cold — cold water shocks them firm.', 5],
      ['Season it down', 'Drain most of the water. Stir in palm oil, sliced onion, blended pepper, crayfish, stock cubes and salt. Let it thicken.', 12],
      ['Fry the plantain', 'Slice the plantain on the diagonal, fry in hot oil until each side is deep gold, and drain on paper.', 8],
    ],
  },
  {
    slug: 'ewa-agoyin',
    name: 'Ewa Agoyin',
    cuisines: ['Nigerian'],
    difficulty: 'medium',
    cookTimeMinutes: 80,
    serves: 4,
    heroIcon: 'bagBeans',
    description: 'Beans mashed down to a soft paste, served with the near-black fried pepper sauce that gives it its name.',
    whatMakesItGood: 'The sauce. Onions and dried pepper fried in palm oil far past the point you would think sensible, until it goes dark, sweet and slightly bitter.',
    ingredients: [
      ['beans_black_eyed', 'Black-eyed beans', 2, 'cup'],
      ['palm_oil', 'Palm oil', 250, 'ml'],
      ['onion_red', 'Red onions', 4, 'piece'],
      ['dry_pepper', 'Dry pepper', 4, 'tbsp'],
      ['stock_cube', 'Stock cubes', 2, 'piece'],
      ['salt', 'Salt', null, null],
      ['bread', 'Bread', 1, 'piece', true],
    ],
    steps: [
      ['Cook the beans soft', 'Boil the beans until they are past tender and starting to break apart. Ewa agoyin wants them mashed, so overcooking is the goal.', 50],
      ['Mash', 'Mash them roughly with a wooden spoon. Some texture left is fine.', 5],
      ['Fry the onions', 'Slice the onions thin and fry slowly in the palm oil until they go from soft to brown to almost black. This takes far longer than feels right. Do not rush it.', 20],
      ['Finish the sauce', 'Stir in the dry pepper and stock cubes, fry two more minutes, then take it off. Spoon over the beans.', 5],
    ],
  },
  {
    slug: 'moin-moin',
    name: 'Moin Moin',
    cuisines: ['Nigerian'],
    difficulty: 'medium',
    cookTimeMinutes: 75,
    serves: 6,
    heroIcon: 'bagBeans',
    description: 'Steamed bean pudding — peeled beans blended with pepper and onion, then steamed in leaves until set.',
    whatMakesItGood: 'The texture when it is right: soft and set, never dense. Blending with as little water as possible is the whole trick.',
    ingredients: [
      ['beans_black_eyed', 'Black-eyed beans', 2, 'cup'],
      ['tatashe', 'Tatashe', 2, 'piece'],
      ['scotch_bonnet', 'Scotch bonnet', 2, 'piece'],
      ['onion_red', 'Red onions', 1, 'piece'],
      ['groundnut_oil', 'Groundnut oil', 120, 'ml'],
      ['egg_chicken', 'Eggs', 3, 'piece', true],
      ['stock_cube', 'Stock cubes', 2, 'piece'],
      ['crayfish', 'Crayfish', 2, 'tbsp', true],
      ['moin_moin_leaf', 'Moin moin leaves', 8, 'piece', true],
      ['salt', 'Salt', null, null],
    ],
    steps: [
      ['Peel the beans', 'Soak the beans twenty minutes, then rub between your palms until the skins float off. Rinse them away. This is tedious and there is no way around it.', 20],
      ['Blend thick', 'Blend the peeled beans with pepper and onion using as little water as you can. A watery blend will never set.', 10],
      ['Season', 'Stir in oil, crayfish, stock cubes and salt. Beat it with a spoon for a minute — it lightens the texture.', 5],
      ['Fill and steam', 'Line the moulds with leaves, pour in the mix, tuck in egg if using. Steam upright with water halfway up the moulds.', 40],
      ['Test', 'A knife should come out clean. If not, steam ten more minutes and check again.', 5],
    ],
  },
  {
    slug: 'pepper-soup-catfish',
    name: 'Catfish Pepper Soup',
    cuisines: ['Nigerian'],
    difficulty: 'easy',
    cookTimeMinutes: 35,
    serves: 4,
    heroIcon: 'bowlSoup',
    description: 'A thin, fiercely aromatic broth with fresh catfish, scent leaf and pepper soup spice.',
    whatMakesItGood: 'It is medicine as much as food. Hot, clear and aromatic — the thing you want when it rains or when you are unwell.',
    ingredients: [
      ['catfish', 'Catfish', 1, 'kg'],
      ['pepper_soup_spice', 'Pepper soup spice', 2, 'tbsp'],
      ['scent_leaf', 'Scent leaf', 1, 'bunch'],
      ['scotch_bonnet', 'Scotch bonnet', 3, 'piece'],
      ['onion_red', 'Red onions', 1, 'piece'],
      ['stock_cube', 'Stock cubes', 2, 'piece'],
      ['uziza_leaf', 'Uziza leaves', 1, 'bunch', true],
      ['salt', 'Salt', null, null],
    ],
    steps: [
      ['Clean the fish', 'Wash the catfish with hot water and a little salt or lime to take off the slime. Cut into steaks.', 10],
      ['Build the broth', 'Bring water to the boil with blended onion and pepper, the pepper soup spice and stock cubes.', 8],
      ['Add the fish', 'Slide the fish in gently and do not stir — catfish falls apart. Shake the pot instead.', 12],
      ['Finish', 'Drop in the scent leaf and uziza in the last two minutes, take it off, and let it sit briefly before serving.', 3],
    ],
  },
  {
    slug: 'ogbono-soup',
    name: 'Ogbono Soup',
    cuisines: ['Nigerian'],
    difficulty: 'medium',
    cookTimeMinutes: 50,
    serves: 5,
    heroIcon: 'potStew',
    description: 'The drawing soup — ground bush mango seed cooked in palm oil until it pulls into long threads.',
    whatMakesItGood: 'The draw. Ogbono is judged entirely on how far it stretches from the plate, and that comes from dissolving it in the oil before any water touches it.',
    ingredients: [
      ['ogbono_ground', 'Ground ogbono', 150, 'g'],
      ['palm_oil', 'Palm oil', 200, 'ml'],
      ['beef', 'Beef', 400, 'g'],
      ['dried_fish', 'Dried fish', 100, 'g'],
      ['crayfish', 'Crayfish', 2, 'tbsp'],
      ['ugu', 'Ugu leaves', 1, 'bunch'],
      ['scotch_bonnet', 'Scotch bonnet', 2, 'piece'],
      ['onion_red', 'Red onions', 1, 'piece'],
      ['stock_cube', 'Stock cubes', 2, 'piece'],
      ['salt', 'Salt', null, null],
    ],
    steps: [
      ['Cook the meat', 'Season and cook the beef until tender. Reserve the stock — it carries the whole soup.', 25],
      ['Dissolve the ogbono', 'Warm the palm oil on low and stir the ground ogbono into it until it dissolves completely and starts to draw. Never add it straight to water or it will clump and never recover.', 8],
      ['Loosen with stock', 'Add the stock little by little, stirring constantly. Too fast and the draw breaks.', 8],
      ['Simmer', 'Add crayfish, dried fish, pepper and stock cubes. Simmer uncovered — covering it kills the draw.', 10],
      ['Add the greens', 'Stir in the ugu, one minute, then off the heat.', 2],
    ],
  },
  {
    slug: 'fried-rice',
    name: 'Nigerian Fried Rice',
    cuisines: ['Nigerian', 'West African'],
    difficulty: 'medium',
    cookTimeMinutes: 55,
    serves: 6,
    heroIcon: 'plateFull',
    description: 'Rice fried with curry, liver and diced vegetables — green, aromatic, and nothing like the Chinese dish it borrows its name from.',
    whatMakesItGood: 'The curry-stained rice and the crunch of vegetables that were barely cooked. It is a party dish that lives or dies on not overcooking anything.',
    ingredients: [
      ['rice_long_grain', 'Long-grain rice', 3, 'cup'],
      ['curry_powder', 'Curry powder', 2, 'tbsp'],
      ['liver', 'Liver', 250, 'g', true],
      ['carrot', 'Carrots', 3, 'piece'],
      ['green_beans', 'Green beans', 150, 'g'],
      ['green_peas', 'Green peas', 100, 'g'],
      ['sweet_corn_tin', 'Tinned sweet corn', 1, 'tin', true],
      ['onion_red', 'Red onions', 2, 'piece'],
      ['groundnut_oil', 'Groundnut oil', 150, 'ml'],
      ['stock_cube', 'Stock cubes', 3, 'piece'],
      ['thyme_dry', 'Dried thyme', 1, 'tsp'],
      ['salt', 'Salt', null, null],
    ],
    steps: [
      ['Parboil the rice', 'Parboil the rice until just short of done, then rinse in cold water and drain completely. Wet rice will steam instead of fry.', 15],
      ['Make the stock', 'Boil the liver with onion, thyme and a stock cube. Dice it small and keep the stock.', 15],
      ['Cook the rice in stock', 'Return the rice to the pot with the curry and just enough stock to colour it. Steam until done but still firm.', 12],
      ['Fry the vegetables', 'On high heat, fry the diced carrots, beans and peas hard and fast — two minutes, no more. They must stay crunchy.', 4],
      ['Bring it together', 'Fold the vegetables and liver through the rice off the heat. Taste, adjust, serve.', 5],
    ],
  },
  {
    slug: 'asaro',
    name: 'Asaro (Yam Porridge)',
    cuisines: ['Nigerian', 'West African'],
    difficulty: 'easy',
    cookTimeMinutes: 45,
    serves: 4,
    heroIcon: 'potStew',
    description: 'Yam cooked down in a palm oil and pepper base until it half-collapses into its own sauce.',
    whatMakesItGood: 'You want it partly mashed and partly whole — some pieces holding their shape, the rest breaking down to thicken the pot.',
    ingredients: [
      ['yam', 'Yam', 1, 'piece'],
      ['palm_oil', 'Palm oil', 150, 'ml'],
      ['tomato', 'Tomatoes', 3, 'piece'],
      ['scotch_bonnet', 'Scotch bonnet', 2, 'piece'],
      ['onion_red', 'Red onions', 1, 'piece'],
      ['crayfish', 'Crayfish', 2, 'tbsp'],
      ['dried_fish', 'Dried fish', 80, 'g', true],
      ['ugu', 'Ugu leaves', 1, 'bunch', true],
      ['stock_cube', 'Stock cubes', 2, 'piece'],
      ['salt', 'Salt', null, null],
    ],
    steps: [
      ['Prepare the yam', 'Peel and cube the yam, rinse, and put it in a pot with water just below the top of the yam.', 10],
      ['Boil with the base', 'Add blended pepper, onion, palm oil, crayfish and stock cubes. Boil covered until the yam softens.', 20],
      ['Break it down', 'Mash about half the yam against the side of the pot and stir. The rest stays in pieces.', 5],
      ['Finish', 'Add the dried fish and the ugu, cook two more minutes, and take it off before the leaves go dull.', 5],
    ],
  },
  {
    slug: 'okra-soup',
    name: 'Okra Soup',
    cuisines: ['Nigerian', 'West African'],
    difficulty: 'easy',
    cookTimeMinutes: 35,
    serves: 5,
    heroIcon: 'potStew',
    description: 'Chopped okra cooked briefly so it keeps its draw and its bite, with palm oil, crayfish and fish.',
    whatMakesItGood: 'Speed. Okra cooked more than a few minutes goes slimy and dull — in and out fast is the entire technique.',
    ingredients: [
      ['okra', 'Okra', 500, 'g'],
      ['palm_oil', 'Palm oil', 120, 'ml'],
      ['crayfish', 'Crayfish', 2, 'tbsp'],
      ['dried_fish', 'Dried fish', 100, 'g'],
      ['scotch_bonnet', 'Scotch bonnet', 2, 'piece'],
      ['onion_red', 'Red onions', 1, 'piece'],
      ['ugu', 'Ugu leaves', 1, 'bunch', true],
      ['stock_cube', 'Stock cubes', 2, 'piece'],
      ['salt', 'Salt', null, null],
    ],
    steps: [
      ['Chop the okra', 'Chop it fine by hand for more draw, or grate it coarsely for texture. Do not blend — blending destroys it.', 10],
      ['Start the base', 'Bring stock, palm oil, blended pepper, crayfish, dried fish and stock cubes to a simmer.', 10],
      ['Add the okra', 'Stir in the okra and cook no more than five minutes. It should still be bright green.', 5],
      ['Finish', 'Fold in the ugu if using, taste for salt, and take it straight off the heat.', 3],
    ],
  },
  {
    slug: 'chicken-stew',
    name: 'Nigerian Chicken Stew',
    cuisines: ['Nigerian', 'West African'],
    difficulty: 'easy',
    cookTimeMinutes: 60,
    serves: 6,
    heroIcon: 'potStew',
    description: 'The red stew that goes with everything — rice, yam, beans, bread. Fried pepper base with browned chicken.',
    whatMakesItGood: 'It is the backbone of Nigerian cooking. Made properly it keeps for days and gets better, and it is the base for half the other dishes in the house.',
    ingredients: [
      ['chicken_whole', 'Whole chicken', 1, 'kg'],
      ['tomato', 'Tomatoes', 6, 'piece'],
      ['tatashe', 'Tatashe', 3, 'piece'],
      ['scotch_bonnet', 'Scotch bonnet', 2, 'piece'],
      ['onion_red', 'Red onions', 2, 'piece'],
      ['tomato_paste', 'Tomato paste', 1, 'tin'],
      ['groundnut_oil', 'Groundnut oil', 200, 'ml'],
      ['stock_cube', 'Stock cubes', 3, 'piece'],
      ['thyme_dry', 'Dried thyme', 1, 'tsp'],
      ['curry_powder', 'Curry powder', 1, 'tsp'],
      ['salt', 'Salt', null, null],
    ],
    steps: [
      ['Season and boil', 'Season the chicken with onion, thyme, curry, a stock cube and salt. Boil in its own moisture until cooked. Keep the stock.', 25],
      ['Fry the chicken', 'Fry the pieces until golden. This is optional but it changes the dish.', 10],
      ['Reduce the blend', 'Blend tomatoes, tatashe, scotch bonnet and one onion, then boil it down until thick.', 12],
      ['Fry the base', 'Fry sliced onion in the oil, add tomato paste, then the reduced blend. Fry until the oil floats clear on top.', 15],
      ['Bring together', 'Add the chicken and enough stock to loosen. Simmer twenty minutes so the flavours settle.', 20],
    ],
  },
  {
    slug: 'gizdodo',
    name: 'Gizdodo',
    cuisines: ['Nigerian'],
    difficulty: 'easy',
    cookTimeMinutes: 40,
    serves: 4,
    heroIcon: 'plateFull',
    description: 'Gizzard and fried plantain tossed in a thick pepper sauce. A party plate that works as a full meal.',
    whatMakesItGood: 'Chewy gizzard against sweet plantain in a sauce thick enough to coat both. Everything must be fried separately or it turns to mush.',
    ingredients: [
      ['gizzard', 'Gizzard', 500, 'g'],
      ['plantain_ripe', 'Ripe plantain', 3, 'piece'],
      ['tatashe', 'Tatashe', 2, 'piece'],
      ['scotch_bonnet', 'Scotch bonnet', 2, 'piece'],
      ['onion_red', 'Red onions', 1, 'piece'],
      ['bell_pepper', 'Bell pepper', 1, 'piece', true],
      ['groundnut_oil', 'Groundnut oil', 250, 'ml'],
      ['stock_cube', 'Stock cubes', 2, 'piece'],
      ['curry_powder', 'Curry powder', 1, 'tsp'],
      ['salt', 'Salt', null, null],
    ],
    steps: [
      ['Cook the gizzard', 'Boil the gizzard with onion, curry, stock cube and salt until tender. It takes longer than you expect.', 25],
      ['Fry separately', 'Fry the gizzard until the edges crisp. Fry the diced plantain until deep gold. Keep them apart.', 12],
      ['Make the sauce', 'Fry blended tatashe and scotch bonnet in a little oil until thick and the oil separates.', 10],
      ['Toss', 'Off the heat, fold the gizzard and plantain through the sauce so both are coated but neither breaks.', 3],
    ],
  },
  {
    slug: 'indomie-stir-fry',
    name: 'Nigerian Indomie Stir-fry',
    cuisines: ['Nigerian'],
    difficulty: 'easy',
    cookTimeMinutes: 15,
    serves: 2,
    heroIcon: 'couscousPlate',
    description: 'Instant noodles cooked the way every Nigerian student learns to — with egg, vegetables and far more pepper than the packet suggests.',
    whatMakesItGood: 'Fifteen minutes, almost no skill, and it tastes far better than the sum of what goes into it.',
    ingredients: [
      ['indomie', 'Indomie', 2, 'pack'],
      ['egg_chicken', 'Eggs', 2, 'piece'],
      ['onion_red', 'Red onions', 1, 'piece'],
      ['carrot', 'Carrots', 1, 'piece', true],
      ['cabbage', 'Cabbage', 100, 'g', true],
      ['scotch_bonnet', 'Scotch bonnet', 1, 'piece'],
      ['groundnut_oil', 'Groundnut oil', 2, 'tbsp'],
      ['stock_cube', 'Stock cubes', 1, 'piece', true],
    ],
    steps: [
      ['Boil the noodles', 'Boil for three minutes only — they will cook further in the pan. Drain and keep a splash of the water.', 4],
      ['Fry the base', 'Fry sliced onion, pepper, carrot and cabbage on high heat for two minutes. Keep them crunchy.', 3],
      ['Scramble the egg', 'Push the vegetables aside, scramble the eggs in the same pan, then mix through.', 3],
      ['Combine', 'Add the noodles, both sachets, and a splash of the reserved water. Toss until everything is coated.', 4],
    ],
  },
  {
    slug: 'yam-and-egg-sauce',
    name: 'Boiled Yam and Egg Sauce',
    cuisines: ['Nigerian'],
    difficulty: 'easy',
    cookTimeMinutes: 30,
    serves: 3,
    heroIcon: 'egg',
    description: 'Boiled yam with a loose tomato and egg sauce. The default Nigerian breakfast when there is yam in the house.',
    whatMakesItGood: 'Twenty minutes from nothing to a full meal, using things almost every kitchen already has.',
    ingredients: [
      ['yam', 'Yam', 1, 'piece'],
      ['egg_chicken', 'Eggs', 4, 'piece'],
      ['tomato', 'Tomatoes', 4, 'piece'],
      ['onion_red', 'Red onions', 1, 'piece'],
      ['scotch_bonnet', 'Scotch bonnet', 1, 'piece'],
      ['groundnut_oil', 'Groundnut oil', 60, 'ml'],
      ['stock_cube', 'Stock cubes', 1, 'piece'],
      ['salt', 'Salt', null, null],
    ],
    steps: [
      ['Boil the yam', 'Peel, cut into rounds, and boil in salted water until a knife slides in easily.', 18],
      ['Fry the sauce', 'Fry sliced onion, then chopped tomato and pepper, until the water cooks off and it thickens.', 8],
      ['Add the eggs', 'Beat the eggs, pour them in, and stir slowly so you get soft folds rather than a scramble.', 4],
    ],
  },
  {
    slug: 'akara',
    name: 'Akara',
    cuisines: ['Nigerian', 'West African'],
    difficulty: 'medium',
    cookTimeMinutes: 45,
    serves: 4,
    heroIcon: 'bagBeans',
    description: 'Peeled beans blended and deep fried into light, airy fritters. Breakfast, usually with pap.',
    whatMakesItGood: 'When the batter is beaten properly they puff hollow and light. A dense akara means it was not beaten enough.',
    ingredients: [
      ['beans_black_eyed', 'Black-eyed beans', 2, 'cup'],
      ['onion_red', 'Red onions', 1, 'piece'],
      ['scotch_bonnet', 'Scotch bonnet', 2, 'piece'],
      ['groundnut_oil', 'Groundnut oil', 400, 'ml'],
      ['salt', 'Salt', null, null],
    ],
    steps: [
      ['Peel the beans', 'Soak twenty minutes and rub off the skins. Rinse them away completely — any skin left shows in the finished akara.', 20],
      ['Blend thick', 'Blend with almost no water, plus the onion and pepper. A runny batter will not hold.', 8],
      ['Beat it', 'Beat the batter hard with a wooden spoon for several minutes until it lightens and holds air. This is what makes them puff.', 6],
      ['Fry', 'Drop spoonfuls into hot oil. They should float and turn quickly. Fry until deep gold and drain.', 10],
    ],
  },
  {
    slug: 'suya',
    name: 'Suya',
    cuisines: ['Nigerian'],
    difficulty: 'medium',
    cookTimeMinutes: 50,
    serves: 4,
    heroIcon: 'cartoonFire',
    description: 'Thin beef coated in spiced groundnut mix and grilled hard over open heat.',
    whatMakesItGood: 'The yaji. Groundnut, pepper and spice crusted onto the meat and toasted by the fire — it is the coating, not the beef, that people queue for.',
    ingredients: [
      ['suya_meat', 'Suya beef', 700, 'g'],
      ['suya_spice', 'Suya spice', 5, 'tbsp'],
      ['groundnut_oil', 'Groundnut oil', 60, 'ml'],
      ['onion_red', 'Red onions', 1, 'piece'],
      ['cabbage', 'Cabbage', 100, 'g', true],
      ['tomato', 'Tomatoes', 2, 'piece', true],
      ['skewer', 'Skewers', 8, 'piece', true],
      ['salt', 'Salt', null, null],
    ],
    steps: [
      ['Slice thin', 'Slice the beef as thin as you can across the grain. Thick suya is tough suya.', 12],
      ['Coat', 'Rub the meat with oil, then press the suya spice on hard so it sticks. Rest it thirty minutes if you have time.', 10],
      ['Skewer and grill', 'Thread onto skewers and grill close to high heat, turning often, until the edges char.', 20],
      ['Finish', 'Dust with more spice off the heat and serve with raw onion, cabbage and tomato.', 5],
    ],
  },
  {
    slug: 'banga-soup',
    name: 'Banga Soup',
    cuisines: ['Nigerian'],
    difficulty: 'involved',
    cookTimeMinutes: 70,
    serves: 5,
    heroIcon: 'potStew',
    description: 'Delta palm fruit soup — rich, oily and heavily spiced, usually with fresh fish or beef.',
    whatMakesItGood: 'The palm fruit concentrate gives a depth nothing else does, and the banga spice mix is unlike any other Nigerian soup.',
    ingredients: [
      ['palm_fruit_concentrate', 'Palm fruit concentrate', 1, 'tin'],
      ['banga_spice', 'Banga spice', 3, 'tbsp'],
      ['catfish', 'Catfish', 800, 'g'],
      ['crayfish', 'Crayfish', 2, 'tbsp'],
      ['scent_leaf', 'Scent leaf', 1, 'bunch'],
      ['onion_red', 'Red onions', 1, 'piece'],
      ['scotch_bonnet', 'Scotch bonnet', 2, 'piece'],
      ['stock_cube', 'Stock cubes', 2, 'piece'],
      ['beef', 'Beef', 300, 'g', true],
      ['salt', 'Salt', null, null],
    ],
    steps: [
      ['Prepare the base', 'Pour the palm fruit concentrate into a pot with water and bring to a boil.', 12],
      ['Reduce', 'Let it boil down uncovered until it thickens noticeably and the oil starts to show.', 20],
      ['Season', 'Add banga spice, crayfish, blended pepper, onion and stock cubes.', 8],
      ['Add the fish', 'Slide in the catfish and do not stir — shake the pot instead. Simmer until cooked through.', 20],
      ['Finish', 'Scent leaf goes in at the very end, off the heat.', 3],
    ],
  },
  {
    slug: 'afang-soup',
    name: 'Afang Soup',
    cuisines: ['Nigerian'],
    difficulty: 'involved',
    cookTimeMinutes: 65,
    serves: 5,
    heroIcon: 'potStew',
    description: 'Efik soup of ground okazi leaf and waterleaf, thick with meat and dried fish.',
    whatMakesItGood: 'The balance of two leaves: waterleaf brings the moisture, okazi brings the body. Neither works alone.',
    ingredients: [
      ['afang', 'Afang leaves', 200, 'g'],
      ['waterleaf', 'Waterleaf', 2, 'bunch'],
      ['palm_oil', 'Palm oil', 200, 'ml'],
      ['beef', 'Beef', 400, 'g'],
      ['ponmo', 'Ponmo', 200, 'g', true],
      ['dried_fish', 'Dried fish', 120, 'g'],
      ['crayfish', 'Crayfish', 3, 'tbsp'],
      ['stock_cube', 'Stock cubes', 2, 'piece'],
      ['scotch_bonnet', 'Scotch bonnet', 2, 'piece'],
      ['salt', 'Salt', null, null],
    ],
    steps: [
      ['Cook the meat', 'Cook the beef and ponmo with onion and stock cube until tender. Keep the stock.', 30],
      ['Prepare the leaves', 'Pound or blend the afang leaves coarsely. Slice the waterleaf and squeeze out excess water.', 12],
      ['Build', 'Add palm oil, crayfish, pepper and dried fish to the meat and stock. Simmer.', 10],
      ['Add waterleaf', 'Stir in the waterleaf first and let it cook down — it releases liquid the afang will absorb.', 6],
      ['Add afang', 'Stir in the afang last, cook five minutes, and take it off. It should be thick, not watery.', 6],
    ],
  },
  {
    slug: 'ewedu-and-gbegiri',
    name: 'Ewedu and Gbegiri',
    cuisines: ['Nigerian'],
    difficulty: 'medium',
    cookTimeMinutes: 55,
    serves: 5,
    heroIcon: 'bowlSoup',
    description: 'The Yoruba pairing — smooth jute leaf soup alongside a bean soup, both spooned over amala with stew.',
    whatMakesItGood: 'Three things on one plate that make no sense alone and complete each other together. Abula, properly.',
    ingredients: [
      ['ewedu', 'Ewedu', 2, 'bunch'],
      ['beans_brown', 'Brown beans', 1, 'cup'],
      ['palm_oil', 'Palm oil', 100, 'ml'],
      ['iru', 'Iru', 1, 'tbsp'],
      ['crayfish', 'Crayfish', 2, 'tbsp'],
      ['stock_cube', 'Stock cubes', 2, 'piece'],
      ['amala_flour', 'Amala flour', 300, 'g', true],
      ['potash', 'Potash', null, null, true],
      ['salt', 'Salt', null, null],
    ],
    steps: [
      ['Cook the gbegiri', 'Boil the beans until completely soft, then sieve or blend and pass through to remove the skins. It should be smooth and pourable.', 35],
      ['Season the gbegiri', 'Return to the pot with palm oil, crayfish and stock cube. Simmer until it thickens slightly.', 10],
      ['Cook the ewedu', 'Boil the ewedu leaves with a little potash and iru, then blend with a broom or blender until smooth and drawing.', 10],
      ['Finish', 'Season the ewedu with crayfish and stock cube. Serve both alongside amala and stew.', 5],
    ],
  },
  {
    slug: 'coconut-rice',
    name: 'Coconut Rice',
    cuisines: ['Nigerian', 'West African'],
    difficulty: 'easy',
    cookTimeMinutes: 50,
    serves: 5,
    heroIcon: 'basketRice',
    description: 'Rice cooked in coconut milk with pepper and vegetables — sweeter and softer than jollof.',
    whatMakesItGood: 'Coconut milk instead of water changes everything: the rice comes out richer and slightly sweet, and it needs far less seasoning.',
    ingredients: [
      ['rice_long_grain', 'Long-grain rice', 3, 'cup'],
      ['coconut_milk', 'Coconut milk', 400, 'ml'],
      ['tomato', 'Tomatoes', 3, 'piece'],
      ['tatashe', 'Tatashe', 2, 'piece'],
      ['scotch_bonnet', 'Scotch bonnet', 1, 'piece'],
      ['onion_red', 'Red onions', 1, 'piece'],
      ['carrot', 'Carrots', 2, 'piece', true],
      ['groundnut_oil', 'Groundnut oil', 100, 'ml'],
      ['stock_cube', 'Stock cubes', 2, 'piece'],
      ['salt', 'Salt', null, null],
    ],
    steps: [
      ['Blend and reduce', 'Blend tomatoes, tatashe, pepper and half the onion, then boil down until thick.', 12],
      ['Fry the base', 'Fry the remaining onion in oil, add the reduced blend, and fry until the oil separates.', 12],
      ['Add coconut milk', 'Pour in the coconut milk and stock cubes, bring to a simmer.', 5],
      ['Cook the rice', 'Stir in washed rice, cover tightly and cook on low. Add hot water only if it dries before the rice softens.', 20],
      ['Rest', 'Off the heat, leave covered five minutes, then fold through the diced carrots.', 5],
    ],
  },
  {
    slug: 'plantain-porridge',
    name: 'Plantain Porridge',
    cuisines: ['Nigerian'],
    difficulty: 'easy',
    cookTimeMinutes: 40,
    serves: 4,
    heroIcon: 'potStew',
    description: 'Unripe plantain cooked down in a palm oil base with greens until thick and soft.',
    whatMakesItGood: 'Unripe plantain holds shape better than yam and brings a firmness porridge otherwise lacks. A good one-pot when there is little in the house.',
    ingredients: [
      ['plantain_unripe', 'Unripe plantain', 4, 'piece'],
      ['palm_oil', 'Palm oil', 120, 'ml'],
      ['tomato', 'Tomatoes', 3, 'piece'],
      ['scotch_bonnet', 'Scotch bonnet', 2, 'piece'],
      ['onion_red', 'Red onions', 1, 'piece'],
      ['crayfish', 'Crayfish', 2, 'tbsp'],
      ['ugu', 'Ugu leaves', 1, 'bunch'],
      ['dried_fish', 'Dried fish', 80, 'g', true],
      ['stock_cube', 'Stock cubes', 2, 'piece'],
      ['salt', 'Salt', null, null],
    ],
    steps: [
      ['Prepare the plantain', 'Peel and cube the unripe plantain. Keep it in water until you are ready or it darkens.', 8],
      ['Boil with the base', 'Cook with blended pepper, onion, palm oil, crayfish and stock cubes, water just below the top.', 20],
      ['Thicken', 'Mash a few pieces against the pot to thicken the sauce, leaving most whole.', 5],
      ['Finish', 'Add dried fish and ugu, two more minutes, off the heat.', 4],
    ],
  },
  {
    slug: 'spaghetti-jollof',
    name: 'Spaghetti Jollof',
    cuisines: ['Nigerian'],
    difficulty: 'easy',
    cookTimeMinutes: 35,
    serves: 4,
    heroIcon: 'couscousPlate',
    description: 'Spaghetti cooked directly in a jollof base so it absorbs the sauce instead of sitting under it.',
    whatMakesItGood: 'Cooking the pasta in the sauce rather than boiling it separately — every strand takes the colour and the pepper.',
    ingredients: [
      ['spaghetti', 'Spaghetti', 500, 'g'],
      ['tomato', 'Tomatoes', 4, 'piece'],
      ['tatashe', 'Tatashe', 2, 'piece'],
      ['scotch_bonnet', 'Scotch bonnet', 2, 'piece'],
      ['onion_red', 'Red onions', 1, 'piece'],
      ['tomato_paste', 'Tomato paste', 1, 'tin'],
      ['groundnut_oil', 'Groundnut oil', 100, 'ml'],
      ['stock_cube', 'Stock cubes', 2, 'piece'],
      ['curry_powder', 'Curry powder', 1, 'tsp'],
      ['sausage', 'Sausage', 4, 'piece', true],
      ['salt', 'Salt', null, null],
    ],
    steps: [
      ['Make the base', 'Blend and reduce the tomatoes, tatashe and pepper, then fry with onion, paste and oil until the oil separates.', 15],
      ['Loosen', 'Add water or stock — roughly enough to cook the pasta — plus stock cubes and curry.', 4],
      ['Cook the pasta in it', 'Break the spaghetti in, stir once, cover and simmer. Stir occasionally so it does not catch.', 12],
      ['Finish', 'When the pasta is done the sauce should be almost gone. Fold in sliced sausage if using.', 4],
    ],
  },
];

/** Expanded to the document shape at seed time. */
export function buildSeedMeals(): Omit<MealAttributes, '_id' | 'createdAt' | 'updatedAt'>[] {
  return SEEDS.map((seed) => {
    const ingredients: MealIngredient[] = seed.ingredients.map(([catalogueId, name, quantity, unit, optional]) => ({
      catalogueId,
      name,
      quantity,
      unit,
      optional: optional ?? false,
    }));

    const steps: MealStep[] = seed.steps.map(([heading, description, estMinutes], i) => ({
      index: i + 1,
      heading,
      description,
      estMinutes,
    }));

    return {
      slug: seed.slug,
      name: seed.name,
      source: 'seed' as const,
      status: 'published' as const,
      cuisines: seed.cuisines,
      difficulty: seed.difficulty,
      cookTimeMinutes: seed.cookTimeMinutes,
      serves: seed.serves,
      whatMakesItGood: seed.whatMakesItGood,
      description: seed.description,
      ingredients,
      steps,
      // Denormalised so matching is a set operation rather than a nested scan.
      ingredientKeys: ingredients.map((i) => i.catalogueId).filter((id): id is string => id !== null),
      heroIcon: seed.heroIcon,
      createdBy: null,
    };
  });
}

export const SEED_MEAL_COUNT = SEEDS.length;
